import GraphQL
@testable import GraphQLGeneratorCore
import Testing

@Suite
struct ResolverGeneratorTests {
    @Test func generate() async throws {
        let bar = try GraphQLObjectType(
            name: "Bar",
            description: "bar",
            fields: [
                "foo": .init(
                    type: GraphQLString,
                    description: "foo",
                ),
            ]
        )
        let schema = try GraphQLSchema(
            query: .init(
                name: "Query",
                fields: [
                    "foo": .init(
                        type: GraphQLString,
                        description: "foo",
                    ),
                    "bar": .init(
                        type: bar,
                        description: "bar",
                    )
                ]
            ),
            types: [
                bar
            ]
        )
        let actual = try ResolverGenerator().generate(schema: schema)
        #expect(
            actual == """
            // Generated by GraphQL Generator
            // DO NOT EDIT - This file is automatically generated

            import Foundation
            import GraphQL
            import GraphQLGeneratorRuntime

            /// Protocol defining all resolver methods for your GraphQL schema
            public protocol GraphQLResolvers: Sendable {
                // MARK: - Query Resolvers

                /// foo
                func foo(context: ResolverContext, info: GraphQLResolveInfo) async throws -> String?

                /// bar
                func bar(context: ResolverContext, info: GraphQLResolveInfo) async throws -> Bar?

            }

            """
        )
    }
}
