import GraphQL
@testable import GraphQLGeneratorCore
import Testing

@Suite
struct SchemaGeneratorTests {
    @Test func generate() async throws {
        let bar = try GraphQLObjectType(
            name: "Bar",
            description: "bar",
            fields: [
                "foo": .init(
                    type: GraphQLString,
                    description: "foo",
                ),
            ]
        )
        let schema = try GraphQLSchema(
            query: .init(
                name: "Query",
                fields: [
                    "foo": .init(
                        type: GraphQLString,
                        description: "foo",
                    ),
                    "bar": .init(
                        type: bar,
                        description: "bar",
                    )
                ]
            ),
            types: [
                bar
            ]
        )
        let actual = try SchemaGenerator().generate(schema: schema)
        let expected = #"""
        // Generated by GraphQL Generator
        // DO NOT EDIT - This file is automatically generated

        import Foundation
        import GraphQL
        import GraphQLGeneratorRuntime

        /// Build a GraphQL schema with the provided resolvers
        public func buildGraphQLSchema(resolvers: GraphQLResolvers) throws -> GraphQLSchema {

            let barType = try GraphQLObjectType(
                name: "Bar",
                description: """
                bar
                """,
            )
            barType.fields = {
                [
                    "foo": GraphQLField(
                        type: GraphQLString,
                        description: """
                        foo
                        """,
                    ),
                ]
            }

            let queryType = try GraphQLObjectType(
                name: "Query",
                fields: [
                    "foo": GraphQLField(
                        type: GraphQLString,
                        description: """
                        foo
                        """,
                        resolve: { source, args, context, info in
                            guard let context = context as? ResolverContext else {
                                throw GraphQLError(
                                        message: "Expected context type ResolverContext but got \(type(of: context))"
                                )
                            }
                            return try await resolvers.foo(context: context, info: info)
                        }
                    ),
                    "bar": GraphQLField(
                        type: barType,
                        description: """
                        bar
                        """,
                        resolve: { source, args, context, info in
                            guard let context = context as? ResolverContext else {
                                throw GraphQLError(
                                        message: "Expected context type ResolverContext but got \(type(of: context))"
                                )
                            }
                            return try await resolvers.bar(context: context, info: info)
                        }
                    ),
                ]
            )
            return try GraphQLSchema(
                query: queryType
            )
        }

        """#
        print(actual.difference(from: expected))
        #expect(
            actual == expected
        )
    }
}
