import GraphQL
@testable import GraphQLGeneratorCore
import Testing

@Suite
struct SchemaGeneratorTests {
    @Test func generate() async throws {
        let bar = try GraphQLObjectType(
            name: "Bar",
            description: "bar",
            fields: [
                "foo": .init(
                    type: GraphQLString,
                    description: "foo",
                ),
            ]
        )
        let schema = try GraphQLSchema(
            query: .init(
                name: "Query",
                fields: [
                    "foo": .init(
                        type: GraphQLString,
                        description: "foo",
                    ),
                    "bar": .init(
                        type: bar,
                        description: "bar",
                    )
                ]
            ),
            types: [
                bar
            ]
        )
        let actual = try SchemaGenerator().generate(schema: schema)
        let expected = #"""
        // Generated by GraphQL Generator
        // DO NOT EDIT - This file is automatically generated

        import Foundation
        import GraphQL
        import GraphQLGeneratorRuntime

        /// Build a GraphQL schema with the provided resolvers
        public func buildGraphQLSchema<Resolvers: ResolversProtocol>(
            resolvers: Resolvers.Type,
            decoder: MapDecoder = .init(),
        ) throws -> GraphQLSchema {
            let bar = try GraphQLObjectType(
                name: "Bar",
                description: """
                bar
                """,
            )
            bar.fields = {
                [
                    "foo": GraphQLField(
                        type: GraphQLString,
                        description: """
                        foo
                        """,
                        resolve: { source, args, context, info in
                            let parent = try cast(source, to: (any BarProtocol).self)
                            let context = try cast(context, to: Context.self)
                            return try await parent.foo(context: context, info: info)
                        }
                    ),
                ]
            }
            let query = try GraphQLObjectType(
                name: "Query",
                fields: [
                    "foo": GraphQLField(
                        type: GraphQLString,
                        description: """
                        foo
                        """,
                        resolve: { source, args, context, info in
                            let context = try cast(context, to: Context.self)
                            return try await Resolvers.Query.foo(context: context, info: info)
                        }
                    ),
                    "bar": GraphQLField(
                        type: bar,
                        description: """
                        bar
                        """,
                        resolve: { source, args, context, info in
                            let context = try cast(context, to: Context.self)
                            return try await Resolvers.Query.bar(context: context, info: info)
                        }
                    ),
                ]
            )
            return try GraphQLSchema(
                query: query
            )
        }

        """#
        print(actual.difference(from: expected))
        #expect(
            actual == expected
        )
    }
}
