import Foundation
import GraphQL

/// Generates a file that simply wraps the SDL so that its available at runtime without moving files.
package struct SDLGenerator {
    package func generate(source: String) throws -> String {
        return """
        // Generated by GraphQL Generator
        // DO NOT EDIT - This file is automatically generated

        let graphQLRawSDL = #\"\"\"
        \(source)
        \"\"\"#
        """
    }
}
