import Foundation
import GraphQL

/// Generates Swift type definitions from GraphQL types
public struct TypeGenerator {
    let schema: GraphQLSchema
    let nameGenerator: SafeNameGenerator

    public init(schema: GraphQLSchema, nameGenerator: SafeNameGenerator = .idiomatic) {
        self.schema = schema
        self.nameGenerator = nameGenerator
    }

    public func generate() throws -> String {
        var output = """
        // Generated by GraphQL Generator
        // DO NOT EDIT - This file is automatically generated

        import Foundation

        """

        // Generate struct for each object type (excluding Query, Mutation, Subscription)
        let typeMap = schema.typeMap
        let objectTypes = typeMap.values.compactMap { $0 as? GraphQLObjectType }

        for objectType in objectTypes {
            // Skip introspection types (prefixed with __) and root operation types
            if objectType.name.hasPrefix("__") ||
               objectType.name == "Query" ||
               objectType.name == "Mutation" ||
               objectType.name == "Subscription" {
                continue
            }

            output += "\n"
            output += try generateStruct(for: objectType)
        }

        // Generate enums
        let enumTypes = typeMap.values.compactMap { $0 as? GraphQLEnumType }
        for enumType in enumTypes {
            // Skip GraphQL internal enums (prefixed with __)
            if enumType.name.hasPrefix("__") {
                continue
            }

            output += "\n"
            output += try generateEnum(for: enumType)
        }

        return output
    }

    private func generateStruct(for type: GraphQLObjectType) throws -> String {
        var output = ""

        // Add description if available
        if let description = type.description {
            output += "/// \(description)\n"
        }

        // Use safe name generator for type name
        let safeTypeName = nameGenerator.swiftTypeName(for: type.name)
        output += "public struct \(safeTypeName): Codable {\n"

        // Generate properties
        let fields = try type.fields()
        for (fieldName, field) in fields {
            if let description = field.description {
                output += "    /// \(description)\n"
            }

            let swiftType = try swiftTypeName(for: field.type)
            let safeFieldName = nameGenerator.swiftMemberName(for: fieldName)
            output += "    public let \(safeFieldName): \(swiftType)\n"
        }

        // Swift auto-generates memberwise initializers for structs, so we don't need to generate one
        output += "}\n"

        return output
    }

    private func generateEnum(for type: GraphQLEnumType) throws -> String {
        var output = ""

        // Add description if available
        if let description = type.description {
            output += "/// \(description)\n"
        }

        // Use safe name generator for enum name
        let safeEnumName = nameGenerator.swiftTypeName(for: type.name)
        output += "public enum \(safeEnumName): String, Codable {\n"

        // Generate cases
        for value in type.values {
            if let description = value.description {
                output += "    /// \(description)\n"
            }
            // Use safe name generator for case names
            let safeCaseName = nameGenerator.swiftMemberName(for: value.name)
            output += "    case \(safeCaseName) = \"\(value.name)\"\n"
        }

        output += "}\n"

        return output
    }

    /// Convert GraphQL type to Swift type name
    private func swiftTypeName(for type: GraphQLType) throws -> String {
        // GraphQLNonNull means the field is required (non-optional)
        if let nonNull = type as? GraphQLNonNull {
            let innerType = try swiftTypeName(for: nonNull.ofType)
            // Remove the optional marker if present
            if innerType.hasSuffix("?") {
                return String(innerType.dropLast())
            }
            return innerType
        }

        // GraphQLList means an array
        if let list = type as? GraphQLList {
            let innerType = try swiftTypeName(for: list.ofType)
            return "[\(innerType)]?"
        }

        // Named types (scalars, enums, objects)
        if let namedType = type as? GraphQLNamedType {
            let typeName = namedType.name
            let swiftType = mapScalarType(typeName)
            // By default, GraphQL fields are nullable, so add optional marker
            return "\(swiftType)?"
        }

        throw GeneratorError.unsupportedType("Unknown type: \(type)")
    }

    /// Map GraphQL scalar types to Swift types
    private func mapScalarType(_ graphQLType: String) -> String {
        switch graphQLType {
        case "ID": return "String"
        case "String": return "String"
        case "Int": return "Int"
        case "Float": return "Double"
        case "Boolean": return "Bool"
        default:
            // For custom types (enums, objects), use safe name generator
            return nameGenerator.swiftTypeName(for: graphQLType)
        }
    }
}

public enum GeneratorError: Error, CustomStringConvertible {
    case unsupportedType(String)

    public var description: String {
        switch self {
        case .unsupportedType(let message):
            return "Unsupported type: \(message)"
        }
    }
}
